"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MakeRankRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_JSON_PATH_FIELD_NUMBER: builtins.int
    OUTPUT_JSON_PATH_FIELD_NUMBER: builtins.int
    input_json_path: builtins.str
    output_json_path: builtins.str
    def __init__(
        self,
        *,
        input_json_path: builtins.str = ...,
        output_json_path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["input_json_path", b"input_json_path", "output_json_path", b"output_json_path"]) -> None: ...

global___MakeRankRequest = MakeRankRequest

@typing.final
class MakeRankResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MakeRankResponse = MakeRankResponse

@typing.final
class CleanDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_JSON_PATH_FIELD_NUMBER: builtins.int
    OUTPUT_JSON_PATH_FIELD_NUMBER: builtins.int
    input_json_path: builtins.str
    output_json_path: builtins.str
    def __init__(
        self,
        *,
        input_json_path: builtins.str = ...,
        output_json_path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["input_json_path", b"input_json_path", "output_json_path", b"output_json_path"]) -> None: ...

global___CleanDataRequest = CleanDataRequest

@typing.final
class CleanDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CleanDataResponse = CleanDataResponse

@typing.final
class AddDetailsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_JSON_PATH_FIELD_NUMBER: builtins.int
    OUTPUT_JSON_PATH_FIELD_NUMBER: builtins.int
    OLD_JSON_PATH_FIELD_NUMBER: builtins.int
    input_json_path: builtins.str
    output_json_path: builtins.str
    old_json_path: builtins.str
    def __init__(
        self,
        *,
        input_json_path: builtins.str = ...,
        output_json_path: builtins.str = ...,
        old_json_path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["input_json_path", b"input_json_path", "old_json_path", b"old_json_path", "output_json_path", b"output_json_path"]) -> None: ...

global___AddDetailsRequest = AddDetailsRequest

@typing.final
class AddDetailsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddDetailsResponse = AddDetailsResponse
