# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api import scoresync_pb2 as api_dot_scoresync__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api/scoresync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScoreSyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRank = channel.unary_unary(
                '/scoresync.ScoreSyncService/MakeRank',
                request_serializer=api_dot_scoresync__pb2.MakeRankRequest.SerializeToString,
                response_deserializer=api_dot_scoresync__pb2.MakeRankResponse.FromString,
                _registered_method=True)
        self.CleanData = channel.unary_unary(
                '/scoresync.ScoreSyncService/CleanData',
                request_serializer=api_dot_scoresync__pb2.CleanDataRequest.SerializeToString,
                response_deserializer=api_dot_scoresync__pb2.CleanDataResponse.FromString,
                _registered_method=True)
        self.AddDetails = channel.unary_unary(
                '/scoresync.ScoreSyncService/AddDetails',
                request_serializer=api_dot_scoresync__pb2.AddDetailsRequest.SerializeToString,
                response_deserializer=api_dot_scoresync__pb2.AddDetailsResponse.FromString,
                _registered_method=True)


class ScoreSyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeRank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRank': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRank,
                    request_deserializer=api_dot_scoresync__pb2.MakeRankRequest.FromString,
                    response_serializer=api_dot_scoresync__pb2.MakeRankResponse.SerializeToString,
            ),
            'CleanData': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanData,
                    request_deserializer=api_dot_scoresync__pb2.CleanDataRequest.FromString,
                    response_serializer=api_dot_scoresync__pb2.CleanDataResponse.SerializeToString,
            ),
            'AddDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDetails,
                    request_deserializer=api_dot_scoresync__pb2.AddDetailsRequest.FromString,
                    response_serializer=api_dot_scoresync__pb2.AddDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scoresync.ScoreSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scoresync.ScoreSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoreSyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scoresync.ScoreSyncService/MakeRank',
            api_dot_scoresync__pb2.MakeRankRequest.SerializeToString,
            api_dot_scoresync__pb2.MakeRankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scoresync.ScoreSyncService/CleanData',
            api_dot_scoresync__pb2.CleanDataRequest.SerializeToString,
            api_dot_scoresync__pb2.CleanDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scoresync.ScoreSyncService/AddDetails',
            api_dot_scoresync__pb2.AddDetailsRequest.SerializeToString,
            api_dot_scoresync__pb2.AddDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
